### ISSUE TITLE
2023.10.20 直播源失效

### ISSUE THREAD

**Issue by guoqidemengxin** [bestpvp/tm#1]
反馈问题 2023.10.20 直播源失效
截图
![1697810108463](https://github.com/bestpvp/tm/assets/121334949/96aa452d-6256-440a-b155-80ffbabc4eb6)

**Comment by CLT2011** [comment]
截图如果无法显示[https://github.com/bestpvp/tm/assets/121334949/96aa452d-6256-440a-b155-80ffbabc4eb6](截图链接)

**Comment by guoqidemengxin** [comment]
截图如果无法显示[截图链接](https://github.com/bestpvp/tm/assets/121334949/96aa452d-6256-440a-b155-80ffbabc4eb6)

**Comment by guoqidemengxin** [comment]
问题已被解决。
